- name: add APT key
  sudo: true
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: add repository
  sudo: true
  apt_repository:
    repo='deb http://apt.newrelic.com/debian/ newrelic non-free'
    state=present
  register: result

- name: apt-get update
  sudo: true
  apt: update_cache=yes
  when: result.changed

- name: install package
  sudo: true
  apt: pkg=newrelic-sysmond
  notify: restart newrelic-sysmond

- name: generate config
  sudo: true
  template:
    src=nrsysmond.cfg.j2
    dest=/etc/newrelic/nrsysmond.cfg
    owner=root
    group=newrelic
    mode=0640
  notify: restart newrelic-sysmond

- name: shutdown if disabled
  sudo: true
  action: service name=newrelic-sysmond state=stopped enabled=no
  when: newrelic.enabled == False
