# Errbit Config
# =============

# The host of your errbit server
host: <%= ENV['HOSTNAME'] || 'errbit.dev' %>

# Enforce SSL connections
enforce_ssl: false

# The email address which email notifications
# will be sent from.
email_from: <%= ENV['ERRBIT_EMAIL_FROM'] || 'no-replay@errbit.dev' %>

# If you turn on this option, email_at_notices can be
# configured on a per app basis, at the App edit page
per_app_email_at_notices: false

# Configure when emails are sent for an error.
# [1,3,7] = 1st, 3rd, and 7th occurence triggers
# an email notification.
email_at_notices: [1, 10, 100]

# Configure whether or not the user should be prompted before resolving an error.
confirm_resolve_err: true

# Add an optional 'username' field to Users.
# Helpful when you need to plug in a custom authentication strategy, such as LDAP.
user_has_username: false

# Allow comments while an issue tracker is configured.
# This is useful if the err is not critical enough to create a ticket,
# but you want to leave a short comment.
allow_comments_with_issue_tracker: true

# Display internal errors in production
# Since this is an internal application, you might like to see what caused Errbit to crash.
# Pull requests are always welcome!
# However, you might be more comfortable setting this to false if your server can be accessed by anyone.
display_internal_errors: true

# Enable Gravatar.
use_gravatar: true
# Default Gravatar image, can be: mm, identicon, monsterid, wavatar, retro.
gravatar_default: monsterid

# GitHub OAuth configuration
<% if ENV['GITHUB_SECRET'] %>
github_authentication: true
github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
github_secret: <%= ENV['GITHUB_SECRET'] %>
# GitHub Permissions to request from user
#   ['repo']        - Allow creating issues for public and private repos.
#   ['public_repo'] - Only allow creating issues for public repos.
#   []              - No permission to create issues on any repos.
github_access_scope: ['repo']
<% end %>

# Configure SMTP settings. If you are running Errbit on Heroku,
#smtp_settings:
#  :address:              ADDRESS
#  :domain:               DOMAIN
#  :port:                 "25"
#  :authentication:       :plain, :login, :cram_md5
#  :enable_starttls_auto: true
#  :user_name:            USERNAME
#  :password:             PASSWORD

smtp_settings:
  :address:              127.0.0.1
  :openssl_verify_mode:  'none'