# Mongoid Configuration
# =====================
#
# Copy this file to config/mongoid.yml and
# modify it accordingly. This file will automatically
# be copied to shared/config on the server when
# `cap deploy:setup` is ran the first time. Be sure
# to place production specific settings there

# set these environment variables on your prod server
<% uri = URI.parse(ENV['MONGODB_URL'] || 'mongo://localhost/errbit_development') %>
<%= Rails.env %>:
  sessions:
    default:
      database: <%= uri.path.gsub(/^\//, '') %>
      hosts:
        - '<%= uri.host %><% if uri.port %>:<%= uri.port %><% end %>'
    <% unless uri.user %>
      username: <%= uri.user %>
      password: <%= uri.password %>
    <% end %>
  options:
    identity_map_enabled: true

