<% uri = URI.parse(ENV['MONGODB_URL'] || 'mongo://localhost/errbit_development') %>
<%= Rails.env %>:
  host: <%= uri.host %>
<% if uri.port %>
  port: <%= uri.port %>
<% end %>
<% unless uri.user %>
  username: <%= uri.user %>
  password: <%= uri.password %>
<% end %>
  database: <%= uri.path.gsub(/^\//, '') %>

