- name: create group
  sudo: true
  group: >
    name={{ deploy_bunny.group }}

- name: create user
  sudo: true
  user: >
    name={{ deploy_bunny.user }}
    group={{ deploy_bunny.group }}

- name: "create /home/{{ deploy_bunny.user }}/.ssh"
  sudo: true
  file: >
    path=/home/{{ deploy_bunny.user }}/.ssh
    state=directory
    owner={{ deploy_bunny.user }}
    group={{ deploy_bunny.group }}
    mode=0700

#- name: "populate /home/{{ deploy_bunny.user }}/.ssh/authorized_keys"
#  sudo: true
#  copy: >
#    src=authorized_keys
#    dest=/home/{{ deploy_bunny.user }}/.ssh/authorized_keys
#    owner={{ deploy_bunny.user }}
#    group={{ deploy_bunny.group }}
#    mode=0600

- name: create /var/www
  sudo: true
  file: >
    path=/var/www
    state=directory
    owner={{ deploy_bunny.user }}
    group={{ deploy_bunny.group }}
    mode=0755

- name: "add 'github.com' to /home/{{ deploy_bunny.user }}/.ssh/known_hosts"
  sudo: true
  lineinfile: >
    dest=/home/{{ deploy_bunny.user }}/.ssh/known_hosts
    state=present
    create=yes
    regexp='github\.com'
    line='github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    owner={{ deploy_bunny.user }}
    group={{ deploy_bunny.group }}
    mode=0600
